name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aws-mern-deploy .
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aws-mern-deploy:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/aws-mern-deploy:latest
      - name: Run Docker Container
        run: |
          docker run -d \
            --name aws-mern-deploy \
            -p 4000:4000 \
            -e MONGO_PASSWORD=${{secrets.MONGO_PASSWORD}} \
            ${{ secrets.DOCKER_USERNAME }}/aws-mern-deploy:latest
